
name: matrix_sphere_Project
packages:
  - packages/**
  - apps/**
  - "*"
scripts:
  bootstrap:
    run: |
      melos clean
      melos bootstrap
      flutter pub get
    description: Membersihkan cache dan menginstal dependensi di semua paket.