name: matrix_sphere_app
description: A monorepo for MatrixSphereApp.
publish_to: 'none'

environment:
  sdk: '>=3.12.1 <4.0.0'

dev_dependencies:
  melos: ^7.8.2

workspace:
  - apps/client_connectivity
  - apps/admin_mikrotik
  - apps/shop_sphere
  - apps/seller_sphere
  - packages/shared_ui
  - packages/shared_services
dependencies:
  go_router: ^14.1.1
  google_generative_ai: ^0.4.7
  image_picker: ^1.2.2
  internet_connection_checker_plus: ^3.1.0
  internet_speed_test: ^1.5.0
  network_info_plus: any
  intl: ^0.20.3 # Disamakan dengan versi yang dibutuhkan oleh shop_sphere
  permission_handler: ^12.0.3
  provider: ^6.1.5+1
  shared_ui: ^1.0.0
