name: matrix_sphere_workspace
description: Matrix Sphere sistem pengendalian dan moderasi akun otomatis yang berfungsi memelihara kepatuhan aturan dalam platform belanja.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.12.1 <4.0.0'

workspace:
  - apps/*
  - packages/*
dependencies:
  animations: ^2.2.0
  cloud_firestore: ^6.6.0
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  intl: ^0.20.3
  provider: ^6.1.5+1
  shared_services: ^1.0.0
  shared_ui: ^0.0.1
