name: matrix_sphere
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.6.0 <4.0.0'

workspace:
  - packages/shared_services
  - packages/shared_ui
  - apps/seller_sphere

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: any
  firebase_core: any
  firebase_crashlytics: any
  firebase_database: any

  go_router: any
  shared_preferences: any
  permission_handler: any
  google_nav_bar: any
  intl: any
  provider: any
  
  camera: any
  logger: any
  curved_navigation_bar: any
  table_calendar: any
  cross_file: any

  shared_services:
    path: packages/shared_services
  shared_ui:
    path: packages/shared_ui

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

flutter:
  uses-material-design: true
  
  assets:
     - images/img_profile-avatar.jpg
