name: shop_sphere
description: "A new Flutter project."
publish_to: 'none'
resolution: workspace
version: 1.0.0+1
environment:
  sdk: '>=3.12.1 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:
  flutter_riverpod:
  shared_ui:
    path: ../../packages/shared_ui
  shared_services:
    path: ../../packages/shared_services
  connectivity_plus:
  google_fonts:
  go_router:
  sizer:
  firebase_core:
  fluttertoast:
  fl_chart:
  flutter_svg:
  permission_handler:
  carousel_slider:
  intl:
  geolocator:
  provider:
  logger:
  collection:
  seller_sphere:
  cloud_firestore:
  uuid:
  implicitly_animated_reorderable_list:
  qr_flutter:
  firebase_crashlytics: ^5.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:

flutter:
  uses-material-design: true
