name: shared_ui
version: 1.0.0
description: A collection of shared services for MatrixSphere.
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_services:
    path: ../shared_services
  mobile_scanner: any
  image_picker: any
  