name: shared_ui
version: 1.0.0
description: A collection of shared services for MatrixSphere.
publish_to: 'none'
resolution: workspace

environment:
  sdk: '>=3.12.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  logger:
  
  get_it:
  shared_preferences:
  routeros_api:
  firebase_core:
  cloud_firestore:
  permission_handler:
  go_router:
  google_fonts:
  flutter_riverpod:
  flutter_svg:
  intl:
  google_nav_bar:

flutter:
  uses-material-design: true
