name: shared_core
version: 1.0.0
description: A collection of shared services for MatrixSphere.
publish_to: 'none'
resolution: workspace

environment:
  sdk: '>=3.12.1 <4.0.0'

dependencies:
  flutter:           # <--- INI WAJIB ADA
    sdk: flutter     # <--- INI WAJIB ADA


flutter:
  uses-material-design: true