// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpmS92ojH_Sijybi7n6QVRFo9Kyz5U9D8',
    appId: '1:359008687014:web:016058a2b5d95b24a9f567',
    messagingSenderId: '359008687014',
    projectId: 'matrixsphere-c3de9',
    authDomain: 'matrixsphere-c3de9.firebaseapp.com',
    databaseURL: 'https://matrixsphere-c3de9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'matrixsphere-c3de9.firebasestorage.app',
    measurementId: 'G-FEGKH863SF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFAyd8hhswA_fsYlzhW6oCdu6irzs7yaA',
    appId: '1:359008687014:android:afabdaa36d53c6e7a9f567',
    messagingSenderId: '359008687014',
    projectId: 'matrixsphere-c3de9',
    databaseURL: 'https://matrixsphere-c3de9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'matrixsphere-c3de9.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBINvlwwv6WoKi3OPSw4Js5kPtEzXi0BRE',
    appId: '1:359008687014:ios:618f33ffc5c579cfa9f567',
    messagingSenderId: '359008687014',
    projectId: 'matrixsphere-c3de9',
    databaseURL: 'https://matrixsphere-c3de9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'matrixsphere-c3de9.firebasestorage.app',
    iosBundleId: 'com.seller.sphereApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBINvlwwv6WoKi3OPSw4Js5kPtEzXi0BRE',
    appId: '1:359008687014:ios:6b9cc8e46de71b69a9f567',
    messagingSenderId: '359008687014',
    projectId: 'matrixsphere-c3de9',
    databaseURL: 'https://matrixsphere-c3de9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'matrixsphere-c3de9.firebasestorage.app',
    iosBundleId: 'com.seller.sphereApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpmS92ojH_Sijybi7n6QVRFo9Kyz5U9D8',
    appId: '1:359008687014:web:6fedbaf52a300390a9f567',
    messagingSenderId: '359008687014',
    projectId: 'matrixsphere-c3de9',
    authDomain: 'matrixsphere-c3de9.firebaseapp.com',
    databaseURL: 'https://matrixsphere-c3de9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'matrixsphere-c3de9.firebasestorage.app',
    measurementId: 'G-SG8J717B9R',
  );
}