import 'dart:async';
import 'package:floor/floor.dart';
import 'package:sqflite/sqflite.dart' as sqflite;

// Import your model and DAO files (assuming they exist in your project)
import '../dao/app_dao.dart';
import '../model/app_access.dart';
import '../../ui/screens/seller_screen.dart';
import '../../ui/screens/approval_screen.dart';
// import 'package:your_package_name/data/model/user_profile.dart';

part '../../presentation/app_database.g.dart'; // This will be generated by floor

@Database(
  version: 1,
  entities: [
    // AppAccess,
    // Seller,
    // ApprovalRequest,
    // Notification,
    // UserProfile,
  ],
)
abstract class AppDatabase extends FloorDatabase {
  // AppDao get appDao;
}

// Database factory implementation
class AppDatabaseFactory {
  static AppDatabase? _instance;

  static Future<AppDatabase> getDatabase() async {
    if (_instance != null) {
      return _instance!;
    }

    return await _initDatabase();
  }

  static Future<AppDatabase> _initDatabase() async {
    return await $FloorAppDatabase
        .databaseBuilder('app_control_database.db')
        .addMigrations([])
        .build();
  }
}