// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpmS92ojH_Sijybi7n6QVRFo9Kyz5U9D8',
    appId: '1:359008687014:web:87735d266c1d383ca9f567',
    messagingSenderId: '359008687014',
    projectId: 'matrixsphere-c3de9',
    authDomain: 'matrixsphere-c3de9.firebaseapp.com',
    databaseURL:
        'https://matrixsphere-c3de9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'matrixsphere-c3de9.appspot.com',
    measurementId: 'G-5VD50MFNS0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFAyd8hhswA_fsYlzhW6oCdu6irzs7yaA',
    appId: '1:359008687014:android:4abea64449f5e96da9f567',
    messagingSenderId: '359008687014',
    projectId: 'matrixsphere-c3de9',
    databaseURL:
        'https://matrixsphere-c3de9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'matrixsphere-c3de9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBINvlwwv6WoKi3OPSw4Js5kPtEzXi0BRE',
    appId: '1:359008687014:ios:b45c323ec27f2f4ea9f567',
    messagingSenderId: '359008687014',
    projectId: 'matrixsphere-c3de9',
    databaseURL:
        'https://matrixsphere-c3de9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'matrixsphere-c3de9.appspot.com',
    iosBundleId: 'com.matrix.sphere',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBINvlwwv6WoKi3OPSw4Js5kPtEzXi0BRE',
    appId: '1:359008687014:ios:a04c8c6c12596562a9f567',
    messagingSenderId: '359008687014',
    projectId: 'matrixsphere-c3de9',
    databaseURL:
        'https://matrixsphere-c3de9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'matrixsphere-c3de9.appspot.com',
    iosBundleId: 'com.matrix.sphereApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpmS92ojH_Sijybi7n6QVRFo9Kyz5U9D8',
    appId: '1:359008687014:web:58893d479e4a5150a9f567',
    messagingSenderId: '359008687014',
    projectId: 'matrixsphere-c3de9',
    authDomain: 'matrixsphere-c3de9.firebaseapp.com',
    databaseURL:
        'https://matrixsphere-c3de9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'matrixsphere-c3de9.appspot.com',
    measurementId: 'G-XKLPW1R0YX',
  );
}
