name: client_connectivity
description: "A new Flutter project."
publish_to: 'none'
resolution: workspace
version: 1.0.0+1
environment:
  sdk: '>=3.12.1 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:
  connectivity_plus:
  google_fonts:
  go_router:
  firebase_core:
  flutter_riverpod:
  fluttertoast:
  fl_chart:
  flutter_svg:
  sizer:
  permission_handler:
  shared_ui:
    path: ../../packages/shared_ui
  shared_services:
    path: ../../packages/shared_services
  logger:
  freezed_annotation:
  intl:
  firebase_crashlytics: ^5.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  build_runner:
  freezed:

flutter:
  uses-material-design: true
