platform :osx, '10.15'

# CocoaPods analytics sends network stats so feel free to disable it.
# cocoapods_disable_stats

flutter_application_path = '..'
# Kembalikan ke jalur standar bawaan Flutter
load File.join(flutter_application_path, 'Flutter', 'ephemeral', 'podhelper.rb')

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_macos_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_macos_build_settings(target)
  end
end
