// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpmS92ojH_Sijybi7n6QVRFo9Kyz5U9D8',
    appId: '1:359008687014:web:58893d479e4a5150a9f567',
    messagingSenderId: '359008687014',
    projectId: 'matrixsphere-c3de9',
    authDomain: 'matrixsphere-c3de9.firebaseapp.com',
    databaseURL: 'https://matrixsphere-c3de9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'matrixsphere-c3de9.firebasestorage.app',
    measurementId: 'G-XKLPW1R0YX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFAyd8hhswA_fsYlzhW6oCdu6irzs7yaA',
    appId: '1:359008687014:android:5d4520e5c7636fcaa9f567',
    messagingSenderId: '359008687014',
    projectId: 'matrixsphere-c3de9',
    databaseURL: 'https://matrixsphere-c3de9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'matrixsphere-c3de9.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBINvlwwv6WoKi3OPSw4Js5kPtEzXi0BRE',
    appId: '1:359008687014:ios:7f1479fb9c13aa0da9f567',
    messagingSenderId: '359008687014',
    projectId: 'matrixsphere-c3de9',
    databaseURL: 'https://matrixsphere-c3de9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'matrixsphere-c3de9.firebasestorage.app',
    iosClientId: '359008687014-l3cjapj4icbeouk1d3avjq2h18mqch5k.apps.googleusercontent.com',
    iosBundleId: 'com.admin.mikrotik',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBINvlwwv6WoKi3OPSw4Js5kPtEzXi0BRE',
    appId: '1:359008687014:ios:f904aec125985675a9f567',
    messagingSenderId: '359008687014',
    projectId: 'matrixsphere-c3de9',
    databaseURL: 'https://matrixsphere-c3de9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'matrixsphere-c3de9.firebasestorage.app',
    iosClientId: '359008687014-euv5lou9t68l23o2h9odu29n23cs42d8.apps.googleusercontent.com',
    iosBundleId: 'com.admin.mikrotikApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpmS92ojH_Sijybi7n6QVRFo9Kyz5U9D8',
    appId: '1:359008687014:web:bd769adad05d4a2fa9f567',
    messagingSenderId: '359008687014',
    projectId: 'matrixsphere-c3de9',
    authDomain: 'matrixsphere-c3de9.firebaseapp.com',
    databaseURL: 'https://matrixsphere-c3de9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'matrixsphere-c3de9.firebasestorage.app',
    measurementId: 'G-WE4ZBSSFWC',
  );
}
