name: client_hotspot
environment:
  sdk: ">=3.12.1 <4.0.0"
dev_dependencies:
  melos: ^7.8.2
workspace:
  # list relative package paths if this package is part of a workspace
  # keep empty list if not using a workspace
  []
melos: {}