// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLNXG3wN-TBja2yldvwE_HKMVf-IC5i0I',
    appId: '1:113584843327:web:2a68364f1662c7dacfe68a',
    messagingSenderId: '113584843327',
    projectId: 'matrixsphere-project',
    authDomain: 'matrixsphere-project.firebaseapp.com',
    databaseURL: 'https://matrixsphere-project-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'matrixsphere-project.firebasestorage.app',
    measurementId: 'G-TTN6MCMND8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOYpg1A3sIMXIWefYVQl18zswoA2ovTGc',
    appId: '1:113584843327:android:6897bc592fb95218cfe68a',
    messagingSenderId: '113584843327',
    projectId: 'matrixsphere-project',
    databaseURL: 'https://matrixsphere-project-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'matrixsphere-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBS87wCTKH68Y33iwX6EJS8-YOrggIeqtg',
    appId: '1:113584843327:ios:54b6d934019765f0cfe68a',
    messagingSenderId: '113584843327',
    projectId: 'matrixsphere-project',
    databaseURL: 'https://matrixsphere-project-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'matrixsphere-project.firebasestorage.app',
    iosBundleId: 'com.example.clienHotspot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBS87wCTKH68Y33iwX6EJS8-YOrggIeqtg',
    appId: '1:113584843327:ios:54b6d934019765f0cfe68a',
    messagingSenderId: '113584843327',
    projectId: 'matrixsphere-project',
    databaseURL: 'https://matrixsphere-project-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'matrixsphere-project.firebasestorage.app',
    iosBundleId: 'com.example.clienHotspot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLNXG3wN-TBja2yldvwE_HKMVf-IC5i0I',
    appId: '1:113584843327:web:fedaf27f34f72ae4cfe68a',
    messagingSenderId: '113584843327',
    projectId: 'matrixsphere-project',
    authDomain: 'matrixsphere-project.firebaseapp.com',
    databaseURL: 'https://matrixsphere-project-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'matrixsphere-project.firebasestorage.app',
    measurementId: 'G-3KK1W7N98Q',
  );
}
