// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD16fxrq8bRBiXYsRc9r6WTKaobYGakWTA',
    appId: '1:887909343137:web:8a86435b882cccaa7275e0',
    messagingSenderId: '887909343137',
    projectId: 'matrixsphere-build',
    authDomain: 'matrixsphere-build.firebaseapp.com',
    databaseURL: 'https://matrixsphere-build-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'matrixsphere-build.firebasestorage.app',
    measurementId: 'G-RKYMW3GFNT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBa0BoPmGgEwZjycWLVMlkIQsOT-nwFD0',
    appId: '1:887909343137:android:0a09b516702121c77275e0',
    messagingSenderId: '887909343137',
    projectId: 'matrixsphere-build',
    databaseURL: 'https://matrixsphere-build-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'matrixsphere-build.firebasestorage.app',
  );

}