name: seller_sphere
description: "A new Flutter project."
publish_to: 'none'

resolution: workspace
version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^2.31.1
  firebase_crashlytics: ^3.5.0
  logger: ^2.0.2+1

  shared_services:
    path: ../../packages/shared_services

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
