name: seller_sphere
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.6.0 <4.0.0'

resolution: workspace

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: any

  shared_ui:
    path: ../../packages/shared_ui
  firebase_core: any
  firebase_crashlytics: any
  shared_services: any
  provider: any
  go_router: any
  curved_navigation_bar: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

flutter:
  uses-material-design: true
