name: shared_services
version: 1.0.0
description: A collection of shared services for MatrixSphere.
publish_to: 'none'
resolution: workspace

environment:
  sdk: '>=3.6.1 <4.0.0'

dependencies:
  cloud_firestore: ^6.7.0
  firebase_core: ^4.12.0
  firebase_crashlytics: ^5.2.5
  firebase_database: ^12.4.5
  flutter:           # <--- INI WAJIB ADA
    sdk: flutter     # <--- INI WAJIB ADA
flutter:
  uses-material-design: true