name: packges_shared
description: Root workspace for MatrixSphereApp monorepo.
publish_to: 'none' # Penting agar root tidak terpublish ke pub.dev

environment:
  sdk: '>=3.12.0 <4.0.0'

dev_dependencies:
  # Tambahkan alat pengembangan yang digunakan oleh semua sub-proyek di sini
  flutter_lints: ^5.0.0