name: Build, Release Client to Repo Home & deploy

on:
  push:
    branches: [ main ]
    paths:
      - 'apps/client_connectivity/**'
      - 'apps/client_connectivity/pubspec.yaml'
  workflow_dispatch:

# Definisi Template untuk reusable steps agar lebih bersih
jobs:
  # 1. BUILD WINDOWS
  build_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with: { channel: 'stable', cache: true }
      - name: Build Windows
        run: |
          flutter config --enable-windows-desktop
          flutter build windows --release
        working-directory: apps/client_connectivity
      - uses: actions/upload-artifact@v4
        with:
          name: build-client-windows
          path: apps/client_connectivity/build/windows/x64/runner/Release/

  # 2. BUILD LINUX
  build_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with: { channel: 'stable', cache: true }
      - name: Build Linux
        run: |
          sudo apt-get update -y
          sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev
          flutter config --enable-linux-desktop
          flutter build linux --release
        working-directory: apps/client_connectivity
      - uses: actions/upload-artifact@v4
        with:
          name: build-client-linux
          path: apps/client_connectivity/build/linux/x64/release/bundle/

  # 3. BUILD ANDROID, WEB, & DEPLOY
  build_mobile_web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with: { java-version: '21', distribution: 'temurin', cache: 'gradle' }
      - uses: subosito/flutter-action@v2
        with: { channel: 'stable', cache: true }

      - name: Install Dependencies
        run: flutter pub get
        working-directory: apps/client_connectivity

      # Build Android
      - name: Build APK
        run: flutter build apk --release
        working-directory: apps/client_connectivity

      # Build Web & Deploy
      - name: Build Web
        run: flutter build web --release
        working-directory: apps/client_connectivity
      
      - name: Deploy to Firebase Hosting
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting --project matrixsphere-c3de9 --non-interactive
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_PATH: apps/client_connectivity

      # Upload APK Artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: apps/client_connectivity/build/app/outputs/flutter-apk/app-release.apk