name: Build and Deploy MatrixSphere

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_android:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - app: SS Shop Sphere
            path: apps/shop_sphere
          - app: SS Seller Sphere
            path: apps/seller_sphere
          - app: CC Client Connectivity
            path: apps/client_coonectivity
          - app: Admin Mikrotik
            path: apps/admin_mikrotik
          - app: Matrix Sphere
            path: .

    steps:
      - name: Fix Directory Permissions
        run: sudo chown -R $USER:$USER ${{ github.workspace }}

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            project: '${{ matrix.path }}/**'

      - uses: subosito/flutter-action@v2
        if: steps.filter.outputs.project == 'true' || github.event_name == 'workflow_dispatch'
        with:
          channel: 'stable'
          cache: true

      # PENTING: Jalankan pub get di folder yang tepat SEBELUM build
      - name: Get Dependencies
        if: steps.filter.outputs.project == 'true' || github.event_name == 'workflow_dispatch'
        run: flutter pub get
        working-directory: ${{ matrix.path }}

      # Build APK dengan working-directory yang benar
      - name: Build APK
        if: steps.filter.outputs.project == 'true' || github.event_name == 'workflow_dispatch'
        run: flutter build apk --release
        working-directory: ${{ matrix.path }}

  deploy_web:
    runs-on: ubuntu-latest
    needs: build # Job ini akan berjalan setelah job 'build' selesai
    steps:
      - uses: actions/checkout@v4
      
      - uses: subosito/flutter-action@v2
        with: 
          channel: 'stable'
          cache: true

      - name: Build Web
        run: flutter build web --release
        # Jika file web ada di subfolder, uncomment baris di bawah:
        # working-directory: apps/Matrix_Sphere 

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting --project matrixsphere-c3de9
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}